#!/bin/bash

echo "🚀 DevTinder Render Deployment"
echo "================================"
echo ""
echo "1. Go to: https://dashboard.render.com/select-repo?type=web"
echo "2. Connect your GitHub account (if not connected)"
echo "3. Select repository: Aryanjstar/DevTinder"
echo "4. Configure:"
echo "   - Name: devtinder-backend"
echo "   - Region: Oregon (US West)"
echo "   - Branch: main"
echo "   - Root Directory: apps/backend"
echo "   - Runtime: Node"
echo "   - Build Command: npm install"
echo "   - Start Command: node src/app.js"
echo "   - Plan: FREE"
echo ""
echo "5. Add Environment Variables:"
echo "   PORT=10000"
echo "   NODE_ENV=production"
echo "   JWT_SECRET=devtinder-jwt-secret-prod-2025"
echo ""
echo "6. After deployment, get your backend URL (e.g., https://devtinder-backend.onrender.com)"
echo ""
echo "7. Update Vercel with backend URL:"
echo "   npx vercel env add VITE_API_BASE_URL"
echo "   Enter: https://YOUR-BACKEND-URL.onrender.com/api"
echo ""
echo "8. Redeploy frontend:"
echo "   cd apps/frontend && npx vercel --prod"
echo ""
echo "Done! Your app will be live on Vercel + Render (100% FREE)"

